### ISSUE TITLE
Show resource consumption on the user's dashboard

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/CrownLabs#117]
In case a huge load is started on the VM, the machine starts responding very slowly. However, the user is not aware of this, hence he may conclude that the cluster is not working properly.
Add a widget in the dashboard that prints the current usage of the user in term of cpu, memory, network, in order to inform when some critical parameters exceed a given threshold.

**Comment by giorio94** [comment]
As discussed during the last meeting, this issue could be solved granting the CrownLabs users the possibility to view an appropriate dashboard in Grafana, presenting the current load of the cluster.

Specifically, this implies:
- [ ] Allowing every CrownLabs user to sign-up in Grafana
- [ ] Adding a button in the user's dashboard redirecting to Grafana
