### ISSUE TITLE
Operator Improvements

### ISSUE THREAD

**Issue by fraborg** [netgroup-polito/CrownLabs#135]
List here and add some possible improvements we could make on the operator

- [x] VM ready status watcher: #138 

- [x] Resources names: #139 

- [x] Namespace filter: #140 

- [x] Expose metrics about its execution and statistics about launched VMs

- [x] Increase the level of information obtained by getting a LabInstance ( #145)

**Comment by giorio94** [comment]
Closing, as all issues have been addressed and the operator evolved much since then
