### ISSUE TITLE
VM status watch

### ISSUE THREAD

**Issue by fraborg** [netgroup-polito/CrownLabs#138]
At the moment we watch the service which exposes the VM to know if it's in Ready state. This control loop sometimes gives some problems and in case of errors the goroutine continues to be executed forever.
To do: think about a different method to get the actual status of the VM.

**Comment by frisso** [comment]
@giorio94 Is this problem still open? Thanks!

**Comment by giorio94** [comment]
I think this could be closed for now. 

The solution in #313 is not yet elegant but introduces a timeout to prevent the goroutine from being executed forever if the VM is deleted before being ready.
