### ISSUE TITLE
The CrownLabs dashboard stops responding

### ISSUE THREAD

**Issue by giorio94** [netgroup-polito/CrownLabs#212]
## Problem description
Sometimes, the CrownLabs dashboard becomes unresponsive and it is forces to close the browser tab. The problem appears to be related with the keycloak token, since it is triggered when it is necessary to reinsert the credentials in a different page (e.g. to access the desktop of a VM or NextCloud after a certain time).

## How to reproduce
Since the bug involves long waiting times, one simple way to reproduce it is (with reference to the chrome browser):
1. Open the crownlabs dashboard
2. Open the developer tools -> Application -> Cookies -> https://auth.crown-labs/...
3. Delete the KEYCLOAK_IDENTITY/SESSION cookies
4. Wait few seconds and the page will stop responding

**Comment by GabriFila** [comment]
Closing due to liqo dashboard usage
