### ISSUE TITLE
Favicon doesn't show in React part of Crownlabs

### ISSUE THREAD

**Issue by GabriFila** [netgroup-polito/CrownLabs#215]
Noticed that the crown favicon is displayed on the [base url](https://crownlabs.polito.it/) but after entering the [app](https://crownlabs.polito.it/userview) and logging in the favicon becomes the default one of the theme. @palexster could this be related to the ingress configuration?

**Comment by palexster** [comment]
Yes, i think the issue with the github logo is the same. We can address them with explicit entries in the ingress object but it may be easier to address them with a subpath for the frontend application.
