### ISSUE TITLE
Add APIs for Course Creation Workflow

### ISSUE THREAD

**Issue by palexster** [netgroup-polito/CrownLabs#227]
So far, the current approach courses and users is done leveraging Python scripts which have to be manually launched. It could be nice to have this workflow exposed via APIs, without having to rewrite all the Python code which is complete and pretty stable.

Proposal: Create a kopf-based [1] operator which consumes dedicated CRDs for course, students, professors ( define APIs to generate CRDs and instrument existing code to handle CRDs reconciliation).

[1]: https://github.com/zalando-incubator/kopf

**Comment by giorio94** [comment]
Closing, as the python scripts have been replaced by the Tenant Operator.
