### ISSUE TITLE
VNCserver shows blank screen when nodes are on medium load

### ISSUE THREAD

**Issue by palexster** [netgroup-polito/CrownLabs#235]
VNCServer does not behave correctly, by presenting a blank screen when scheduled on a node with medium load. In particular, vnserver is started long before the network becomes available in the VM.

Strategy:
- Let VNCService wait for network-online.target before being started and noVNC consequently.
- Reduce the amount of enabled services in the VM to reduce disk operations (mandb, log-rotate)

**Comment by giorio94** [comment]
Closing for the moment, since after #238 this issue has no longer been reported. 
Feel free to reopen if the problem occurs again.
