### ISSUE TITLE
non-optimal running vms windows on professor view

### ISSUE THREAD

**Issue by michele6000** [netgroup-polito/CrownLabs#236]
**Improvements:** 

- [x]  Change dimension of running vms on professor view, is better to use all the screen height
- [x]   <s>Change padding and margin, it is better to have a narrower list.</s>
- [x]  Change text color on list, now is black on green background, maybe we can keep black and use a lighter green (Lime green for example)
- [x]  GitHub logo is disappeared

**Bug fix:**

- [x]  The button to kill a vm is disappeared

**Comment by GabriFila** [comment]
I agree! Only thing I would remove from this issue the hourglass part because I believe it is related to other issues #237 #126

**Comment by michele6000** [comment]
After setting the dynamic resizing of the running vms window, I thought superfluous to tighten the margins, if you agree I would leave it like this.

**Comment by frisso** [comment]
Agreed.
