### ISSUE TITLE
Selected LabInstance index

### ISSUE THREAD

**Issue by s41m0n** [netgroup-polito/CrownLabs#257]
User type: Professor
Device: Any

When selecting a LabInstance sometimes, due to wrong indexes assigned to those rows, multiple laboratories are selected the same time. This happens when you are a Professor, meaning that there are both LabInstances as a normal user and as a privileged one.

![ok](https://user-images.githubusercontent.com/24576567/82123220-76ab9180-9798-11ea-9e3d-0b29f690ccb1.png)

![ko](https://user-images.githubusercontent.com/24576567/82123226-7b704580-9798-11ea-9b72-3398bf9ad960.png)

**Comment by giorio94** [comment]
Reopening, since this bug is still present in the pre-production environment, running the most up-to-date code
