### ISSUE TITLE
Improve registration/login experience

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/CrownLabs#87]
- [x] The email should come from a well-identified sender. Currently it comes from "netgroup,polito@gmail.com", which doesnt' identify who is currently sending the message. Better to change the sender in "CrownLabs service administrator <netgroup.polito@gmail.com>", so that people feel easier to identify what is this message about.

- [x] The email with the link to register to the service lasts only 12 hours. It should be extended to 48 hours. Otherwise professors will spend a huge amount of time re-registering students who did not click on the link in time.

- [x]  The email received by the student MUST tell explicitly the username that has to be used to register. Currently this information is missing, so the student has no idea about his account.

- [x] The login page (https://auth....) should be changed in order to ask explicitly for the username. Currently it asks for username or email address; if you try to log-in with the latter, the service refuses the access. Alternatively (honestly, preferred) the login procedure should support the email as well.

- [ ] Not mandatory, but it should be nice to send another email to the person telling him that the registration procedure has been completed successfully, possibly with a link to update his personal data (password, user, etc).

**Comment by palexster** [comment]
Closing.
