### ISSUE TITLE
Possible update of Kubernetes API endpoints

### ISSUE THREAD

**Issue by fracappa** [netgroup-polito/CrownLabs#903]
Hello everyone.

I would like to report that front-end reports messages about using outdated API endpoints.
For example, when I access to my CL account I have a  "You are using an outdated endpoint"  red line on my profile picture.

This could be related to the recent Kubernetes cluster updates that have been carrying out.

Additionally, I would suggest to check whether outdated API endpoints are also used within the back-end.

Regards,
Francesco

**Comment by QcFe** [comment]
Ciao Francesco,

I suspect this is related to #901, should be fixed already, but we need to create a new release for this to go in production.

Can you check if this is gone in [preproduction](https://preprod.crownlabs.polito.it)?

**Comment by fracappa** [comment]
Hi @QcFe .
Yes I confirm it. The problem is not present in the preproduction version.

Thanks!
