### ISSUE TITLE
"Drive" homepage button points to old (BSc) Nextcloud instance instead of MSc Nextcloud instance

### ISSUE THREAD

**Issue by Mattia013** [netgroup-polito/CrownLabs#915]
**Describe the bug**
When I connect to Crownlabs with my MSc account and try to access the Nextcloud Drive, it points to my BSc Nextcloud Drive instance.

**To Reproduce**
1. Go to Crownlabs homepage
2. Click on Drive
3. Click on Files (top-left corner)
4. Click on Setting (bottom-left corner)
5. Check the WebDAV link (the final part of the link contains the matricola number)

**Expected behavior**
It should point to the MSc Drive.

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.1.1 arm64
 - Browser: Firefox
 - Version: 132.0.2 aarch64

**Comment by Mattia013** [comment]
Hi @QcFe !
By BSc and MSc drive, I mean the Nextcloud instances related to my BSc and MSc matricula.

In particular, when I log in to Crownlabs with my new MSc matricula, I would expect to click on the "Drive" button and be redirected to the Nextcloud instance of that particular account (which is also the one mounted in the VMs I spawn), instead the link points to the Nextcloud instance of my old account.
This is inconvenient, since I cannot access the files I upload from my non-persistent VMs.

**Comment by QcFe** [comment]
This is pretty weird to be honest, there's nothing like a link between the two matriculas. Have you tried through incognito mode as well? If it work that way, then it's likely some sort of long session that for some reason is kept live with NextCloud... In that case logging out should be enough to fix your main browser profile as well

**Comment by Mattia013** [comment]
In incognito everything worked as exptected.

I tried clearing the browser history, and after logging in, everything works also in my main browser profile.
Thank you for helping!

**Comment by QcFe** [comment]
NP!
Either way sooner or later the nextcloud based mydrive experience will be dismissed in favor to cloud native storage (if we manage to set it up meaninfully...)
